---
name: billing-demo-app

type: rails

up:
- homebrew:
  - openssl
  - shopify/shopify/mysql-client:
      or:
      - mysql
      conflicts:
      - mysql-connector-c
  - phantomjs
- ruby: 2.3.1
- custom:
    name: copy config/keys.yml
    met?: test -f config/keys.yml
    meet: cp config/keys.sample.yml config/keys.yml
- bundler
- railgun
- database:
    bootstrap: bin/rake db:setup ; bin/rake db:test:prepare
    migrate: bin/rake db:migrate db:test:prepare
    host: billing-demo-app.railgun
    user: root
    password: ''
    database: db/development.sqlite3

server:
  port: 40017

commands:
  console:
    desc: start a rails console
    run: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    desc: run tests
    run: bin/rake test
open:
  My Application: https://billing-demo-app.myshopify.io
  billing-demo-app: https://billing-demo-app.myshopify.io
